### ISSUE TITLE
Mentor of the Week Google Form and E-mail Copy

### ISSUE THREAD

**Issue by mikepromazo** [promazo/Content-Team#11]
@Lupecasas - can you share the updated Mentor of the Week Google Form and the email we plan to send to mentors?

**Comment by Lupecasas** [comment]
Yes I have shared it with you and Emily, I had it on the wrong email. I will also attach it here:

https://docs.google.com/forms/d/e/1FAIpQLSeVKpt4fgCrKa08wTURErW_TtPuRRul_K2BnOzXhznAf3JkTA/viewform
